services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_COOKIE_DOMAIN=${VITE_COOKIE_DOMAIN}
    ports:
      - '80:80'
    restart: unless-stopped
